[package]
name = "tauri-plugin-ankidroid"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
authors = ["Tauri AnkiDroid Plugin Contributors"]
description = "Tauri plugin for integrating with AnkiDroid on Android"
license = "MIT OR Apache-2.0"
links = "tauri-plugin-ankidroid"

[lib]
name = "tauri_plugin_ankidroid"
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = ["tauri-plugin"]
tauri-plugin = ["dep:tauri", "dep:tauri-plugin"]

[build-dependencies]
tauri-plugin = { version = "2", default-features = false, features = ["build"], optional = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
tauri = { workspace = true, optional = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
ndk = "0.9"
ndk-context = "0.1"
base64 = "0.21"

[dev-dependencies]
tokio = { version = "1.0", features = ["full", "test-util"] }

# Tool configuration metadata
[package.metadata.cargo-machete]
ignored = ["thiserror"]  # Used for error handling, might be needed later

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]