[package]
name = "tauri-plugin-ankidroid"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
authors = ["Tauri AnkiDroid Plugin Contributors"]
description = "Tauri plugin for integrating with AnkiDroid on Android"
license = "MIT OR Apache-2.0"
links = "tauri-plugin-ankidroid"

[lib]
name = "tauri_plugin_ankidroid"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
ndk = "0.9"
ndk-context = "0.1"

[dev-dependencies]
tokio = { version = "1.0", features = ["full", "test-util"] }